twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    globals:
        twig_app_name: '%env(APP_NAME)%'
        twig_image_dir: 'images/'

when@test:
    twig:
        strict_variables: true
